#/bin/bash
echo обновляем систему...
apt update && apt upgrade -y
echo устанавливаем необходимые пакеты...
apt install apt-transport-https ca-certificates curl software-properties-common
echo добавляем GPG ключи...
curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
echo добавляем репозиторий Docker...
echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian $(lsb\_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
echo обновляем список доступных пакетов...
apt update
переключаемся на репозиторий Docker...
apt-cache policy docker-ce
устанавливаем Docker...
apt install docker-ce
docker_status=$(systemctl status docker) #вот эта залупа под вопросом
echo "$docker_status"
echo меняем конфигурацию Docker для сетевых интерфейсов...
sed -i 's|ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd\.sock|ExecStart=/usr/bin/dockerd --mtu 1450 -H fd:// --containerd=/run/containerd/containerd.sock|' /lib/systemd/system/docker.service
echo перезапускаем демона systemctl...
systemctl daemon-reload
Docker успешно установлен :)
